version: '3.3'

services:
  db:
    build: ./mongodb
    restart: unless-stopped
    env_file:
      - db.env

  backend:
    build: ./backend
    restart: always
    env_file:
      - db.env
    depends_on:
      - db

  change_contacts:
    build: ./change_contacts
    restart: always
    env_file:
      - db.env
      - admin.env
    volumes:
      - static-data:/app/templates/static
    command: ./entrypoint.sh
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./logs:/var/log/nginx
      - static-data:/usr/share/nginx/html/static/change-contacts
    depends_on:
      - backend
volumes:
  static-data: