version: '3.1'

services:

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    hostname: redis

  backend:
    build: .
    image: altai
    container_name: altai
    restart: always
    depends_on:
      - redis
    ports:
      - "80:80"
    links:
      - redis

  worker:
    build: .
    image: worker
    container_name: worker
    entrypoint: celery
    command: -A app.celery worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis
