version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    restart: always
    env_file:
      - mail.env
      - db.env
    ports:
      - '8000:8000'
    depends_on:
      - db

  change_contacts:
    build: ./change_contacts
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - db.env
      - mail.env
    volumes:
      - static-data:/app/templates/static
    command: ./entrypoint.sh
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '80:80'
    volumes:
      - static-data:/usr/share/nginx/html/static/change-contacts
    depends_on:
      - backend
volumes:
  static-data: